FROM node:18 as builder

WORKDIR /app/builder
COPY . .

RUN npm install
RUN npm run core:build

FROM node:18-alpine

WORKDIR /app

ENV GRPC_HEALTH_PROBE_VERSION="v0.3.1"

RUN GRPC_HEALTH_PROBE_VERSION=v0.3.1 && \
    wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /bin/grpc_health_probe

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nestjs -u 1001

COPY --from=builder /app/builder/dist ./dist
COPY --from=builder /app/builder/package.json ./

ENV HUSKY_SKIP_INSTALL=1

RUN npm install --prod --ignore-scripts
RUN npm run prisma

USER nestjs

EXPOSE 3000

CMD ["npm", "run", "core:prod"]
