# Source: tomas-service/charts/capsula-api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rest-service
  namespace: default
  labels:
    helm.sh/chart: rest-service-0.1.17
    app.kubernetes.io/name: rest-service
    app.kubernetes.io/instance: rest-service
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    version: "latest"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: rest-service
    app.kubernetes.io/instance: rest-service
---
# Source: tomas-service/charts/capsula-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-service
  labels:
    helm.sh/chart: rest-service-0.1.17
    app.kubernetes.io/name: rest-service
    app.kubernetes.io/instance: rest-service
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    version: "latest"
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rest-service
      app.kubernetes.io/instance: rest-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rest-service
        app.kubernetes.io/instance: rest-service
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: rest-service
          image: "blacksinx/paycraft-mono-repo_rest:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 25
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          env:
            - name: PORT
              value: '3000'
            - name: APPLICATION_NAME
              valueFrom:
                secretKeyRef:
                  key: applicationName
                  name: rest-secret
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: redisUrl
                  name: rest-secret
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: mongoUrl
                  name: rest-secret
            - name: CORE_SERVICE_GRPC
              valueFrom:
                secretKeyRef:
                  key: coreServiceGrpc
                  name: rest-secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: databaseUrl
                  name: rest-secret
            - name: SERVICE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: firebaseServiceAccount
                  name: rest-secret

          resources:
            limits:
              cpu: 900m
              memory: 990Mi
            requests:
              cpu: 80m
              memory: 40Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: "api-paycraft.alphacode.cl"
      http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              service:
                name: rest-service
                port:
                  number: 3000
